site_name: Catalyst Studios Guides
site_url: https://catalyst-studios.github.io/catalystguides/
repo_url: https://github.com/Catalyst-Studios/catalystguides/
repo_name: catalystguides
edit_uri: edit/main/docs/
copyright: Catalyst Studios™ | Built by <a href='https://github.com/ArcTrooper210' class='arc'>ArcTrooper</a>
strict: !ENV [ENABLE_STRICT, true]
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/Catalyst-Studios
          name: GitHub
        - icon: fontawesome/brands/discord
          link: https://discord.gg/YCHPXeW9GZ
          name: Discord
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CatalystModpack
          name: Twitter
extra_css:
    - assets/stylesheets/extra.css
extra_javascript:
    - assets/javascripts/extra.js
    - assets/javascripts/tablesort.js
    - assets/javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
    name: material
    locale: en
    custom_dir: overrides
    logo: assets/img/catyLogo.png
    favicon: assets/img/catyLogo.png
    font: 
        text: Exo 2
    icon:
        repo: fontawesome/brands/github
        edit: material/pencil
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.indexes
        - toc.follow
        - navigation.top
        - announce.dismiss
        - navigation.footer
        - content.action.edit
        - content.tooltips
        - content.footnote.tooltips
        - content.code.copy
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: custom
          accent: custom
          toggle:
            icon: material/weather-night
            name: Switch to light mode
        
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          primary: custom
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode

plugins:
    - search
    - mkdocs-video
    - mkdocs-audio
    - autolinks # may adversely affect build times
    - open-in-new-tab
    - meta-descriptions:
        enabled: !ENV [META_DESCRIPTIONS, false]
    - git-revision-date-localized:
        type: timeago
        fallback_to_build_date: false
        enable_creation_date: true
        enabled: !ENV [ENABLED_GIT_REVISION_DATE, false]
        strict: true
    - git-authors:
        show_contribution: true
        show_email_address: false
        fallback_to_empty: true
        sort_authors_by: contribution
        enabled: !ENV [ENABLED_GIT_AUTHORS, false]
        strict: !ENV [ENABLE_STRICT_GIT_AUTHORS, false]
    - minify:
        minify_html: !ENV [ENABLE_MINIFY, false]
        minify_js: !ENV [ENABLE_MINIFY, false]
        minify_css: !ENV [ENABLE_MINIFY, false]
        cache_safe: true
    - autorefs:
        resolve_closest: true
    - awesome-pages:
        collapse_single_pages: true
    - glightbox:
        draggable: false
        auto_caption: true
    - tags
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
        permalink: true
    - tables
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji 
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
                case: lower
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - pymdownx.extra
    - pymdownx.fancylists
    - pymdownx.progressbar
